ALTER TABLE leads ADD COLUMN IF NOT EXISTS hubspot_contact_id VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS hubspot_company_id VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS hubspot_deal_id VARCHAR(100);
